workflows:
  build-ios:
    name: Build iOS App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean & Get Dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS (no signing)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
