name: lbpool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ^3.7.2

dependencies:
  connectivity_plus: 6.1.3
  firebase_messaging: ^15.2.5
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  flutter_localizations:
    sdk: flutter
  intl: any
  internet_connection_checker_plus: ^2.7.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/connection_lost.png"

flutter_native_splash:
  color: "#ffffff" # fond d'écran
  image: assets/images/logo_lbpool_mini.png
  android: true
  ios: true
  android_gravity: center
